#!/bin/sh
# postinst script
#
# see: dh_installdeb(1)

set -e

if [ -f /etc/dpkg/origins/default ]; then
rm -f /etc/dpkg/origins/default
fi

ln -sf /etc/dpkg/origins/duzeru /etc/dpkg/origins/default

update-grub

exit 0


